name: CI/CD Next.js to DigitalOcean

on:
  push:
    branches: [master]

jobs:
  # ========================
  # 1. CI Job (build & test)
  # ========================
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  # ========================
  # 2. CD Job (deploy ke server)
  # ========================
  cd:
    runs-on: ubuntu-latest
    needs: ci # hanya jalan kalau CI sukses
    environment: Production

    steps:
      - name: Deploy & Build on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          port: 22
          script: |
            cd /var/www/celeparty.com/celeparty-fe

            echo "ğŸ“¥ Pulling latest code..."
            git fetch origin master
            git reset --hard origin/master

            echo "ğŸ“¦ Installing dependencies..."
            npm ci

            echo "âš’ï¸ Building app..."
            npm run build

            echo "ğŸš€ Restarting app with pm2..."
            pm2 restart celeparty.com || pm2 start npm --name "celeparty.com" -- run start
