name: CI/CD Next.js to DigitalOcean

on:
  push:
    branches: [master]

jobs:
  ci:
    # ========================
    # 1. CI Job (build & test)
    # ========================
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"
          check-latest: true

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

  cd:
    # ========================
    # 2. CD Job (deploy ke server)
    # ========================
    runs-on: ubuntu-latest
    needs: ci # hanya jalan kalau CI sukses
    environment: Production

    steps:
      - name: Deploy & Build on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          timeout: 120s
          command_timeout: 30m
          request_pty: false
          debug: true
          script: |
            cd /var/www/celeparty.com/celeparty-fe

            echo "üì• Pulling latest code..."
            git fetch origin master
            git reset --hard origin/master

            echo "üßπ Cleaning up disk space..."
            rm -rf node_modules .next package-lock.json .cache
            npm cache clean --force || true

            echo "üì¶ Installing dependencies..."
            npm install --legacy-peer-deps --no-audit --no-fund --silent

            echo "‚öíÔ∏è Building app..."
            export NODE_OPTIONS="--max-old-space-size=4096" 
            npm run build --silent

            echo "üöÄ Restarting app with pm2..."
            pm2 restart celeparty.com || pm2 start npm --name "celeparty.com" -- run start
