name: Deploy Celeparty FE

on:
  push:
    branches: [master]

jobs:
  # ========================
  # 1. CI Job (build & test)
  # ========================
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        #echo "üì¶ Installing dependencies..."
        run: npm install --legacy-peer-deps

      - name: Build
        #echo "‚öíÔ∏è Building app..."
        run: npm run build

      # ========================
      # 2. CD Job (deploy ke server)
      # ========================

      - name: Upload build to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          source: ".next,public,package.json,package-lock.json"
          target: "/var/www/celeparty.com/celeparty-fe"

      - name: Run app on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/celeparty.com/celeparty-fe
            npm install --omit=dev

            echo "üöÄ Restarting app with pm2..."
            pm2 restart celeparty.com || pm2 start npm --name "celeparty.com" -- run start
